/*    ==Scripting Parameters==

    Source Database Engine Edition : Microsoft Azure SQL Database Edition
    Source Database Engine Type : Microsoft Azure SQL Database

    Target Database Engine Edition : Microsoft Azure SQL Database Edition
    Target Database Engine Type : Microsoft Azure SQL Database
*/

/****** Object:  View [dbo].[EMMS_TIMESERIES_CONSUMPTION]    Script Date: 04-10-2017 18:00:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[EMMS_TIMESERIES_CONSUMPTION] 
AS
SELECT 
	A.TAG_ID,
	A.Asset_ID,
	A.Wages_type,
	EU.Description UOM,
	A.ISEXPONENTIAL,
	A.DATE_TIME START_TIME,
	B.DATE_TIME END_TIME,
	FORMAT(B.DATE_TIME,'dd-MMM-yyyy') as DATEID,
	MONTH(B.DATE_TIME) MONTHID,
	FORMAT(B.DATE_TIME,'MMM') Monthly,
	YEAR(B.DATE_TIME) YearID,
	Concat(FORMAT(B.DATE_TIME,'HH'),':00') Hourly,
	FORMAT(B.DATE_TIME,'mm') MinuteID,
	A.CONSUMPTION START_CONSUMPTION,
	B.CONSUMPTION END_CONSUMPTION , 
	(CASE WHEN A.ISEXPONENTIAL='Y' THEN (B.CONSUMPTION-A.CONSUMPTION) ELSE B.CONSUMPTION END) ACTUAL_CONSUMPTION ,
	EET.ConsumptionTarget,
	WUC.unit_cost
FROM
	(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY TAG_ID,DATE_TIME) ROWID,
		TAG_ID,
		ETD.Asset_ID,
		ETD.Wages_type,
		ETD.UOM,
		DATE_TIME,
		ETD.ISEXPONENTIAL,
		CONSUMPTION 
	FROM 
		EMMS_TAG_TIMESERIESDATA ETT INNER JOIN EMMS_TAG_DETAILS ETD ON 
		ETT.TAG_ID=ETD.ID 
) A
INNER JOIN
(
SELECT * 
FROM (
	SELECT 
		ROW_NUMBER() OVER (ORDER BY TAG_ID,DATE_TIME) ROWID,
		TAG_ID,
		ETD.Asset_ID,
		ETD.Wages_type,
		ETD.UOM,
		DATE_TIME,
		CONSUMPTION 
	FROM 
		EMMS_TAG_TIMESERIESDATA ETT INNER JOIN EMMS_TAG_DETAILS ETD ON 
		ETT.TAG_ID=ETD.ID
) A WHERE A.ROWID>1) B
ON A.ROWID=B.ROWID-1  INNER JOIN EMMS_MASTER_WAGES_UOM EU ON B.uom=EU.ID
LEFT JOIN WAGES_UNIT_COST_USD WUC ON FORMAT(B.Date_time,'yyyy')=WUC.Year_ID and B.Wages_type=WUC.Wages_type
AND B.Asset_ID=WUC.Asset_ID
LEFT JOIN EMMS_Equipment_target EET
ON MONTH(B.DATE_TIME)=EET.MonthID AND YEAR(B.DATE_TIME)=EET.YearID 
AND B.Asset_ID=EET.AssetID AND B.Wages_Type=EET.Wages_Type
WHERE A.DATE_TIME<B.DATE_TIME

GO

