/*    ==Scripting Parameters==

    Source Database Engine Edition : Microsoft Azure SQL Database Edition
    Source Database Engine Type : Microsoft Azure SQL Database

    Target Database Engine Edition : Microsoft Azure SQL Database Edition
    Target Database Engine Type : Microsoft Azure SQL Database
*/

/****** Object:  View [dbo].[EMMS_TIMESERIES_DATA]    Script Date: 04-10-2017 18:00:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[EMMS_TIMESERIES_DATA] 
AS
SELECT 
	A.TAG_ID,
	A.Asset_ID,
	A.Wages_type,
	A.UOM,
	A.ISEXPONENTIAL,
	A.DATE_TIME START_TIME,
	B.DATE_TIME END_TIME,
	A.CONSUMPTION START_CONSUMPTION,
	B.CONSUMPTION END_CONSUMPTION , 
	(CASE WHEN A.ISEXPONENTIAL='Y' THEN (B.CONSUMPTION-A.CONSUMPTION) ELSE B.CONSUMPTION END) ACTUAL_CONSUMPTION 
FROM
	(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY TAG_ID,DATE_TIME) ROWID,
		TAG_ID,
		ETD.Asset_ID,
		ETD.Wages_type,
		ETD.UOM,
		DATE_TIME,
		ETD.ISEXPONENTIAL,
		CONSUMPTION 
	FROM 
		EMMS_TAG_TIMESERIESDATA ETT INNER JOIN EMMS_TAG_DETAILS ETD ON 
		ETT.TAG_ID=ETD.ID 
) A
INNER JOIN
(
SELECT * 
FROM (
	SELECT 
		ROW_NUMBER() OVER (ORDER BY TAG_ID,DATE_TIME) ROWID,
		TAG_ID,
		ETD.Asset_ID,
		ETD.Wages_type,
		ETD.UOM,
		DATE_TIME,
		CONSUMPTION 
	FROM 
		EMMS_TAG_TIMESERIESDATA ETT INNER JOIN EMMS_TAG_DETAILS ETD ON 
		ETT.TAG_ID=ETD.ID
) A WHERE A.ROWID>1) B
ON A.ROWID=B.ROWID-1 
WHERE A.DATE_TIME<B.DATE_TIME



GO

